version: "3.7"
services:
  postgres:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: udacity
      POSTGRES_USER: udacity
      POSTGRES_DB: udacity
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  cassandra-node1:
    image: bitnami/cassandra:3.11.6
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
      - CASSANDRA_CLUSTER_NAME=cassandra
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=udacity
      - CASSANDRA_USER=udacity
    restart: always
    volumes:
      - ./tmp/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml
      - ./tmp/cassandra/var/lib/cassandra:/var/lib/cassandra
  cassandra-load-keyspace:
      image: bitnami/cassandra:3.11.6
      depends_on:
        - cassandra-node1
      volumes:
        - ./data/cassandra_schema.cgl:/schema.cql
      command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra-node1 -u udacity -p udacity -f /schema.cql"